load data_hwk1.mat;
argentina_dat = data_hwk1{1,1};
us_dat = data_hwk1{1,2};
tb_us = (us_dat(6,:) - us_dat(7,:)) ./ us_dat(2,:);
tb_arg = (argentina_dat(6,:) - argentina_dat(7,:)) ./ argentina_dat(2,:);
argentina_dat = log(argentina_dat);
us_dat = log(us_dat);

s = size(us_dat);
t = s(2);

t1 = 1:t;
t2 = t1.^2;
X = [ones(1, t); t1; t2];
XX = [X X X X];
y = [us_dat(2,:) us_dat(3,:) us_dat(4,:) us_dat(5, :)]';
common_beta_us = inv(XX * XX') * (XX * y);
proj = common_beta_us(1) + common_beta_us(2) * t1 + common_beta_us(3) * t2;
detrended = us_dat(:,:) - proj;
std_us_y = std(detrended(2,:) * 100);
std_us_c = std(detrended(3,:) * 100);
std_us_g = std(detrended(4,:) * 100);
std_us_i = std(detrended(5,:) * 100);
serial_corr_y = autocorr(detrended(2,:), 1);
serial_corr_c = autocorr(detrended(3,:), 1);
serial_corr_g = autocorr(detrended(4,:), 1);
serial_corr_i = autocorr(detrended(5,:), 1);
fprintf('US common-trend sigma_y: %.4f\n', std_us_y);
fprintf('US common-trend sigma_c / sigma_y: %.4f\n', std_us_c / std_us_y);
fprintf('US common-trend sigma_g / sigma_y: %.4f \n', std_us_g / std_us_y);
fprintf('US common-trend sigma_i / sigma_y: %.4f \n', std_us_i / std_us_y);
fprintf('US common-trend Correlations with output\n');
fprintf('Output: %.4f\n', corr(detrended(2,:)', detrended(2,:)'));
fprintf('Consumption: %.4f\n', corr(detrended(2,:)', detrended(3,:)'));
fprintf('Government: %.4f\n', corr(detrended(2,:)', detrended(4,:)'));
fprintf('Investment: %.4f\n', corr(detrended(2,:)', detrended(5,:)'));
fprintf('US common-trend serial correlations\n');
fprintf('Output: %.4f\n', serial_corr_y(2));
fprintf('Consumption: %.4f\n', serial_corr_c(2));
fprintf('Government: %.4f\n', serial_corr_g(2));
fprintf('Investment: %.4f\n', serial_corr_i(2));


s = size(us_dat);
t = s(2);

detrended_us_y = detrend(t, us_dat(2,:));
detrended_us_tb_y = detrend(t, tb_us);
detrended_us_c = detrend(t, us_dat(3,:));
detrended_us_g = detrend(t, us_dat(4,:));
detrended_us_i = detrend(t, us_dat(5,:));
std_us_y = std(detrended_us_y * 100);
std_us_c = std(detrended_us_c * 100);
std_us_g = std(detrended_us_g * 100);
std_us_i = std(detrended_us_i * 100);
std_us_tb_y = std(detrended_us_tb_y * 100);
serial_corr_y = autocorr(detrended_us_y, 1);
serial_corr_c = autocorr(detrended_us_c, 1);
serial_corr_g = autocorr(detrended_us_g, 1);
serial_corr_i = autocorr(detrended_us_i, 1);
serial_corr_tb_y = autocorr(detrended_us_tb_y, 1);
fprintf('US non-common-trend sigma_y: %.4f\n', std_us_y);
fprintf('US non-common-trend sigma_c / sigma_y: %.4f\n', std_us_c / std_us_y);
fprintf('US non-common-trend sigma_g / sigma_y: %.4f \n', std_us_g / std_us_y);
fprintf('US non-common-trend sigma_i / sigma_y: %.4f \n', std_us_i / std_us_y);
fprintf('US non-common-trend sigma_tb/y: %.4f \n', std_us_tb_y);
fprintf('US non-common-trend Correlations with output\n');
fprintf('Output: %.4f\n', corr(detrended_us_y', detrended_us_y'));
fprintf('Consumption: %.4f\n', corr(detrended_us_y', detrended_us_c'));
fprintf('Investment: %.4f\n', corr(detrended_us_y', detrended_us_g'));
fprintf('Government: %.4f\n', corr(detrended_us_y', detrended_us_i'));
fprintf('TB/y: %.4f\n', corr(detrended_us_y', detrended_us_tb_y'));
fprintf('US non-common-trend serial correlations\n');
fprintf('Output: %.4f\n', serial_corr_y(2));
fprintf('Consumption: %.4f\n', serial_corr_c(2));
fprintf('Government: %.4f\n', serial_corr_g(2));
fprintf('Investment: %.4f\n', serial_corr_i(2));
fprintf('TB/y: %.4f\n', serial_corr_tb_y(2));

s = size(argentina_dat);
t = s(2);

t1 = 1:t;
t2 = t1.^2;
X = [ones(1, t); t1; t2];
XX = [X X X X];
y = [argentina_dat(2,:) argentina_dat(3,:) argentina_dat(4,:) argentina_dat(5, :)]';
common_beta_arg = inv(XX * XX') * (XX * y);
proj = common_beta_arg(1) + common_beta_arg(2) * t1 + common_beta_arg(3) * t2;
detrended = argentina_dat(:,:) - proj;
std_arg_y = std(detrended(2,:) * 100);
std_arg_c = std(detrended(3,:) * 100);
std_arg_g = std(detrended(4,:) * 100);
std_arg_i = std(detrended(5,:) * 100);
serial_corr_y = autocorr(detrended(2,:), 1);
serial_corr_c = autocorr(detrended(3,:), 1);
serial_corr_g = autocorr(detrended(4,:), 1);
serial_corr_i = autocorr(detrended(5,:), 1);
fprintf('Argentina common-trend sigma_y: %.4f\n', std_arg_y);
fprintf('Argentina common-trend sigma_c / sigma_y: %.4f\n', std_arg_c / std_arg_y);
fprintf('Argentina common-trend sigma_g / sigma_y: %.4f \n', std_arg_g / std_arg_y);
fprintf('Argentina common-trend sigma_i / sigma_y: %.4f \n', std_arg_i / std_arg_y);
fprintf('Argentina common-trend Correlations with output\n');
fprintf('Output: %.4f\n', corr(detrended(2,:)', detrended(2,:)'));
fprintf('Consumption: %.4f\n', corr(detrended(2,:)', detrended(3,:)'));
fprintf('Government: %.4f\n', corr(detrended(2,:)', detrended(4,:)'));
fprintf('Investment: %.4f\n', corr(detrended(2,:)', detrended(5,:)'));
fprintf('Argentina common-trend serial correlations\n');
fprintf('Output: %.4f\n', serial_corr_y(2));
fprintf('Consumption: %.4f\n', serial_corr_c(2));
fprintf('Government: %.4f\n', serial_corr_g(2));
fprintf('Investment: %.4f\n', serial_corr_i(2));

s = size(argentina_dat);
t = s(2);

detrended_arg_tb_y = detrend(t, tb_arg);
detrended_arg_y = detrend(t, argentina_dat(2,:));
detrended_arg_c = detrend(t, argentina_dat(3,:));
detrended_arg_g = detrend(t, argentina_dat(4,:));
detrended_arg_i = detrend(t, argentina_dat(5,:));
std_arg_y = std(detrended_arg_y * 100);
std_arg_c = std(detrended_arg_c * 100);
std_arg_g = std(detrended_arg_g * 100);
std_arg_i = std(detrended_arg_i * 100);
std_arg_tb_y = std(detrended_arg_tb_y * 100);
serial_corr_y = autocorr(detrended_arg_y, 1);
serial_corr_c = autocorr(detrended_arg_c, 1);
serial_corr_g = autocorr(detrended_arg_g, 1);
serial_corr_i = autocorr(detrended_arg_i, 1);
serial_corr_tb_y = autocorr(detrended_arg_tb_y, 1);
fprintf('Argentina non-common-trend sigma_y: %.4f\n', std_arg_y);
fprintf('Argentina non-common-trend sigma_c / sigma_y: %.4f\n', std_arg_c / std_arg_y);
fprintf('Argentina non-common-trend sigma_g / sigma_y: %.4f \n', std_arg_g / std_arg_y);
fprintf('Argentina non-common-trend sigma_i / sigma_y: %.4f \n', std_arg_i / std_arg_y);
fprintf('Argentina non-common-trend sigma_tb/y: %.4f \n', std_arg_tb_y);
fprintf('Argentina non-common-trend Correlations with output\n');
fprintf('Output: %.4f\n', corr(detrended_arg_y', detrended_arg_y'));
fprintf('Consumption: %.4f\n', corr(detrended_arg_y', detrended_arg_c'));
fprintf('Government: %.4f\n', corr(detrended_arg_y', detrended_arg_g'));
fprintf('Investment: %.4f\n', corr(detrended_arg_y', detrended_arg_i'));
fprintf('TB/y: %.4f\n', corr(detrended_arg_y', detrended_arg_tb_y'));
fprintf('Argentina non-common-trend serial correlations\n');
fprintf('Output: %.4f\n', serial_corr_y(2));
fprintf('Consumption: %.4f\n', serial_corr_c(2));
fprintf('Government: %.4f\n', serial_corr_g(2));
fprintf('Investment: %.4f\n', serial_corr_i(2));
fprintf('Tb/y: %.4f\n', serial_corr_tb_y(2));


function [detrended] = detrend(t, dat)
t1 = 1:t;
t2 = t1.^2;
y = dat';
X = [ones(1, t); t1; t2];
beta = inv(X * X') * (X * y);
proj = beta(1) + beta(2) * t1 + beta(3) * t2;
detrended = dat - proj;
end