---
  title: Problem Set 9
  author: Guy Aridor
---
    
1) 
a) i)  The research question that Angrist and Evans wish to answer deals with understanding the relationship between fertility and labor supply. Namely they wish to understand the causal link between fertility to the work effort of both men and women. To do this they will consider the marginal effect of an additional child on the person's labor force decision.

ii) The authors consider two instruments.

The first instrument they consider is a "sibling sex mix" instrument in families of two or more children. Thus the instrument they use is a dummy variable that is 1 if the second child matches the sex of the first child and 0 if it does not.

The second instrument considers using twins to construct the instruments. Thus the instrument they use is simply a dummy variable that is 1 if the mother has twins and 0 if she does not.

iii) For the first instrument they justify its exogeneity by arguing that sex mix is virtually randomly assigned. They argue that it is a valid instrument since parents of same-sex siblings are more likely to go on to have an additional child.

For the second instrument the exogeneity of the instrument rests on the assumption that all women are equally likely to have twins. However, they note that this is not necessarily the case as twinning probabilities can be correlated with observed characteristics of the mother. However this is okay since if all these demographic characteristics are observed then these factors can be controlled for in 2SLS. The validity of the instrument is derived from the fact that there is a relationship between having twins and having more children.

iv) Their conclusions are that once we add the instruments it confirms that OLS estimates exaggerate the extent to which additional children leads to a reduction in female labor supply. They also show that the effects of children on labor supply are almost absent among college-educated women and women whose husbands have high wages. They also show that labor-market behavior of married men is insensitive to the number of children.

```{r}
library(sem)

data <- read.dta("/Users/garidor/Desktop/first-year/spring/metrics/ps9/fertility.dta")

```

  